<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>自定义错误</title>
</head>
<body>
  <script type="text/javascript">
    try{
      var a = 100, b = 0;
      var c = a / b;
      if(c === Infinity){
        throw new Error("result is Infinity", "07.error.html");
      }
    }catch(err){
      console.log(err);
    }finally{
      //finally 都执行
      console.log("finally ...");
    }

    /*
    嵌套错误处理：
    如果内层没有编写catch语句块，那么错误触发时会像外传递，交给最近的一个catch处理；
    如果内层编写catch语句，内层自己处理。
    */
    
  </script>

</body>
</html>
